version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: telmo (just a test)
    #   - MONGO_INITDB_ROOT_USERNAME=telmo
    #   MONGO_INITDB_ROOT_PASSWORD: secretpass (just a test)
    env_file:
      - ./env/mongo.env
    # networks: (optional, Docker creates automatically some network)
    #   - my-network-name
  backend:
    build: ./backend #(goes inside of backend folder and follows Dockerfile instructions)
    # context: ./backend
    # dockerfile: Dockerfile-dev #if Docker file has a different name
    # args:
    #   some-arg: 1
    ports:
      - '80:80'
      # - '5000:5000' if multiple ports exposed
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  # frontend:

# Only named volumes needed here, no bind mounts or anonymous volumes
volumes: 
  data:
  logs: